## Week 11-Matrix operations

In this tutorial I am going to show you the quick tools to do all the previous operations using numpy!!

You can do everything using one command in numpy, This tutorial will show you the following:

h = f+g   to add vectors or matrices

np.ident(n) to create an identity matrix of size nxn

np.dot(u,v)  to compute the dot product of vectors u and v

np.matmul(A,x)  to compute the matrix vector multiplication Ax

np.matmul(A,B)  to compute the matrix matrix multiplication AB



I have recorded a video guide for this week. It is partparticularly helpful on the Jacobi method:
    
https://youtu.be/nkvd9Qt-ka4

In [1]:
#
import numpy as np

# create 2 vectors called f anf g, just give them some numbers.
f = np.array([1,2,4])
g = np.array([3,1,2])

print('f: ',f)
print('g: ',g)

# and now add the up and assign it to a variable called h

h = f+g

print('the sum is: ')
print(h)



f:  [1 2 4]
g:  [3 1 2]
the sum is: 
[4 3 6]


same thing for the matrix addition!


In [2]:
import numpy as np

# create two matrices as before
mat1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
mat2 = np.array([[-1,-2,-3],[-4,-5,-6],[-7,-8,-9],[-10,-11,-12]])

# add them up! - note it should come to xeros with these two matrices
matsum = mat1+mat2
print('matrix sum')
print(matsum)


matrix sum
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


create an identity matrix of some size we use:

In [3]:
import numpy as np
# now compare your codes to using the numpy tools to do the above
# create a 5x5 identity matrix
im = np.identity(5)
print('identity matrix')
print(im)



identity matrix
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


and what about dot products of vectors:

Dot product calculates the sum of the two vectors’ multiplied elements. Dot Product returns a scalar number as a result. The dot product is useful in calculating the projection of vectors. Dot product in Python also determines orthogonality and vector decompositions. 

The dot product of two vectors a = [a1, a2, …, an] and b = [b1, b2, …, bn] is defined as:

${\displaystyle \mathbf {\color {red}a} \cdot \mathbf {\color {blue}b} =\sum _{i=1}^{n}{\color {red}a}_{i}{\color {blue}b}_{i}={\color {red}a}_{1}{\color {blue}b}_{1}+{\color {red}a}_{2}{\color {blue}b}_{2}+\cdots +{\color {red}a}_{n}{\color {blue}b}_{n}}{\displaystyle \mathbf {\color {red}a} \cdot \mathbf {\color {blue}b} =\sum _{i=1}^{n}{\color {red}a}_{i}{\color {blue}b}_{i}={\color {red}a}_{1}{\color {blue}b}_{1}+{\color {red}a}_{2}{\color {blue}b}_{2}+\cdots +{\color {red}a}_{n}{\color {blue}b}_{n}}$

In [4]:
# do a dot product
u = np.array([6,4,3,5,4])
v = np.array([1,2,2,3,4])
dp = np.dot(u,v)
print('numpy dot product is ',dp)



numpy dot product is  51


finally the matrix vector and matrix -matrix multiplications can be performed in one command


In [5]:
# create two matrices
A = np.array([[4,2,1],[1,3,1],[2,3,6]])
B = np.array([[4,2,1],[1,3,1],[2,3,6]])
# and some vector x
x = np.array([4,3,2])

# the matrix vector product can be computed by:
b = np.matmul(A,x)
print('matrix multiply vector')
print(b)

# the matrix matrix product can be computed using the same command:

C = np.matmul(A,B)
print('matrix multiply matrix ')
print(C)


matrix multiply vector
[24 15 29]
matrix multiply matrix 
[[20 17 12]
 [ 9 14 10]
 [23 31 41]]
